joint_limits:
  j1:
    has_velocity_limits: false
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0
  j2:
    has_velocity_limits: false
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0
  j3:
    has_velocity_limits: false
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0
  j4:
    has_velocity_limits: false
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0
  j5:
    has_velocity_limits: false
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0
  j6:
    has_velocity_limits: false
    max_velocity: 1000.0
    has_acceleration_limits: false
    max_acceleration: 0
